repos:
  - repo: local
    hooks:
      # 0) update_record_count.pyに実行権限を付与
      - id: ensure-update-record-count-exec
        name: Ensure update_record_count.py is executable
        language: system
        entry: chmod +x scripts/update_record_count.py
        pass_filenames: false

      # 1) ファイル名規則
      - id: filename-convention
        name: Check CSV filename convention
        language: python
        entry: scripts/hooks/check_filename.py
        files: ^data/mishearing/.+\.csv$
        pass_filenames: true

      # 2) datapackage を自動生成
      - id: build-datapackage
        name: Build datapackage.json
        language: python
        entry: scripts/build_datapackage.py
        pass_filenames: false         # 変更ファイルに依存しない

      # 3) Frictionless validate
      - id: frictionless-validate
        name: Frictionless validate
        language: system
        entry: bash -c 'frictionless validate datapackage.json'
        pass_filenames: false

      # 4) Pytest
      - id: pytest
        name: Run pytest
        language: system
        entry: pytest
        pass_filenames: false

      # 5) バッジ・README自動更新
      - id: update-record-count
        name: Update record count badge and README
        language: python
        entry: scripts/update_record_count.py
        pass_filenames: false
