name: validate
on: [push, pull_request]

jobs:
  frictionless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pip install frictionless pytest
      - name: Build datapackage.json
        run: python scripts/build_datapackage.py
      - name: Filename convention
        run: python scripts/hooks/check_filename.py $(git ls-files 'data/mishearing/**/*.csv')
      - name: Frictionless validate
        run: frictionless validate datapackage.json
      - name: Pytest
        run: pytest

  update-count:
    needs: frictionless        # validate ジョブ名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Recompute record count
        run: python scripts/update_record_count.py
      - name: Commit & push if changed
        shell: bash
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          if git status --porcelain | grep -qE '^\s*M|^\s*\?\?'; then
            git add badges/records.json README.md
            git commit -m "chore: update record count (auto) [skip ci]"
            git push
          else
            echo "No change in record count."
